### ISSUE TITLE
Save hosts

### ISSUE THREAD

**Issue by machawk1** [jcushman/warcgames#1]
I overwrote my hosts file from step 4 in the README. It would be useful to either backup the current hosts file or provide a warning in the README of the ramifications. I realize this is a no-brainer but I was a little too enthusiastic about trying your package, so proceeded blindly.

**Comment by jcushman** [comment]
That's terrible! My apologies. It definitely appends to hosts rather than overwriting on my machine. Not sure what happened here -- let me know if you can figure it out.

Until we figure it out, I updated the README to simply instruct you to edit the file, without any fancy terminal command that could do something unexpected.
